### ISSUE TITLE
client crash wenn i open click gui or join on a server

### ISSUE THREAD

**Issue by SadBlock54** [xLiquidCode/ReverseClientIssues#3]
client crash wenn i open click gui or join on a server

crash logs

---- Minecraft CrasherUtil Report ----
// Who set us up the TNT?

Time: 16/09/19 22.46
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.crash.CrashReportCategory.firstTwoElementsOfStackTraceMatch(Unknown Source)
	at net.minecraft.crash.CrashReport.makeCategoryDepth(Unknown Source)
	at net.minecraft.crash.CrashReport.makeCategory(Unknown Source)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntityAt(Unknown Source)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntity(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(Unknown Source)
	at net.minecraft.client.Minecraft.runGameLoop(Unknown Source)
	at net.minecraft.client.Minecraft.run(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at InjectionAPI.inject(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.crash.CrashReportCategory.firstTwoElementsOfStackTraceMatch(Unknown Source)
	at net.minecraft.crash.CrashReport.makeCategoryDepth(Unknown Source)
	at net.minecraft.crash.CrashReport.makeCategory(Unknown Source)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntityAt(Unknown Source)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntity(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(Unknown Source)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player555'/6587, l='MpServer', x=-107,50, y=23,00, z=-153,16]]
	Chunk stats: MultiplayerChunkCache: 9, 9
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 529,00,4,00,-927,00 - World: (529,4,-927), Chunk: (at 1,0,1 in 33,-58; contains blocks 528,0,-928 to 543,255,-913), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 2234849665 game time, 992322554 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Player555'/6587, l='MpServer', x=-107,50, y=23,00, z=-153,16]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.14-SNAPSHOT:9e17ca3:294) <- TacoSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(Unknown Source)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Unknown Source)
	at net.minecraft.client.Minecraft.run(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at InjectionAPI.inject(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 10 (amd64) version 10.0
	CPU: <unknown>
	Java Version: 1.8.0_181-0-ojdkbuild, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 188997256 bytes (180 MB) / 484442112 bytes (462 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 4 total; -Xmx1024M -Xverify:none -Xbootclasspath:AAL\lib\rt.jar;AAL\lib\charsets.jar;AAL\lib\deploy.jar;AAL\lib\javaws.jar;AAL\lib\jce.jar;AAL\lib\jfr.jar;AAL\lib\jfxswt.jar;AAL\lib\jsse.jar;AAL\lib\management-agent.jar;AAL\lib\plugin.jar;AAL\lib\resources.jar -XX:+DisableAttachMechanism
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Reverse
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 500 GL version 4.6.0 - Build 26.20.100.7158, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: §9Sky Blue 32x.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.8.8_HD_U_H8
	Render Distance Chunks: 3
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7158
	OpenGlRenderer: Intel(R) HD Graphics 500
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by xLiquidCode** [comment]
Ok, i'll will look into it.
